### ISSUE TITLE
Wrong color picked up when moving pointer from left to right 

### ISSUE THREAD

**Issue by saikat0511** [tuberry/color-picker#32]
I am using gnome 41.2 on Arch 

Extension behaves as expected when pointer is moved from right to left but shows and picks up wrong color when moved from left to right. Attaching a small screen capture for a demo of my issue...

https://user-images.githubusercontent.com/57610828/146398252-f098d339-c50d-43e0-a897-c4a8034afefa.mp4

**Comment by tuberry** [comment]
Confirmed, but it only occurs when moving fast (not when moving by keyboard), and stationary results are not affected. Actually, I don't know why this is happening. :(

**Comment by saikat0511** [comment]
The issue occurs for me even when moving the cursor slow or when stationary.

Moving by keyboard works fine and and that's what I am using right now

**Comment by tuberry** [comment]
I'm sure it's an upstream bug, but sorry, I don't have much time to delve into it now.

**Comment by saikat0511** [comment]
No worries! Since a workaround is available I can live with it for now. Is this issue not present in older gnome releases?

**Comment by andyfitz** [comment]
![Kooha-08-08-2022-10-32-48](https://user-images.githubusercontent.com/1276715/183317704-240ca365-ec41-4083-a0ae-6fc930431eb4.gif)

I get a similar issue but red and green. 

I believe this is related to proportional scaling, 
it happens when i'm at 150% scale but not at 200%

**Comment by tuberry** [comment]
@andyfitz Could that reproduce with internal color picker of GNOME Shell?
```bash
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Screenshot --method org.gnome.Shell.Screenshot.PickCol
```

**Comment by tuberry** [comment]
Now we have a label for preview besides the icon. There should be no such problem:
![sc](https://user-images.githubusercontent.com/17917040/183420453-624406cf-2658-42b5-9e2c-a33da7ddd425.png)


@saikat0511 Color-picking is to capture a 1px*1px size picture under the cursor to detect it's color, because the preview icon moves slower than the cursor, when quickly moving to the right, the cursor will overlap with the icon resulting in capturing the color of the icon. Since the fancy icon comes from the GNOME Shell, I consider it as an upstream bug. Could you please open an issue in GNOME Shell's GitLab repo?

@andyfitz Sorry,  proportional scaling is unavailable on my system (Arch / GNOME 43) so that I'm not sure that they are the same reason.

**Comment by andyfitz** [comment]
@tuberry  Sorry I meant fractional scaling

You can enable it by setting:


> gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

This isn't officially supported by GNOME however so it's not a huge issue.

I could not reproduce the red and green results using 

> gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Screenshot --method org.gnome.Shell.Screenshot.PickColor

**Comment by tuberry** [comment]
@andyfitz Reproduced on 1960x1080 / 125% / Wayland with both two pickers. But I don't have a clue about the cause for now. :(
